cloudbeat:
  # Defines how often an event is sent to the output
  period: 30s
  fetchers:
  - name: kube-api
  - name: process
    directory: "/hostfs"
    processes:
      etcd:
      kube-apiserver:
      kube-controller:
      kube-scheduler:
      kubelet:
        config-file-arguments:
        - config
  - name: file-system
    patterns: [
      "/hostfs/etc/kubernetes/scheduler.conf",
      "/hostfs/etc/kubernetes/controller-manager.conf",
      "/hostfs/etc/kubernetes/admin.conf",
      "/hostfs/etc/kubernetes/kubelet.conf",
      "/hostfs/etc/kubernetes/manifests/etcd.yaml",
      "/hostfs/etc/kubernetes/manifests/kube-apiserver.yaml",
      "/hostfs/etc/kubernetes/manifests/kube-controller-manager.yaml",
      "/hostfs/etc/kubernetes/manifests/kube-scheduler.yaml",
      "/hostfs/etc/systemd/system/kubelet.service.d/10-kubeadm.conf",
      "/hostfs/var/lib/kubelet/config.yaml",
      "/hostfs/etc/kubernetes/pki/*.crt",
      "/hostfs/etc/kubernetes/pki/*.key",
      "/hostfs/var/lib/etcd",
      "/hostfs/etc/kubernetes/pki"
    ]

# =================================== Kibana ===================================
setup.kibana:

  # Kibana Host
  host: "http://host.docker.internal:5601"
# =============================== Elastic Cloud ================================

# These settings simplify using Cloudbeat with the Elastic Cloud (https://cloud.elastic.co/).

# The cloud.id setting overwrites the `output.elasticsearch.hosts` and
# `setup.kibana.host` options.
# You can find the `cloud.id` in the Elastic Cloud web UI.
#cloud.id:

# The cloud.auth setting overwrites the `output.elasticsearch.username` and
# `output.elasticsearch.password` settings. The format is `<user>:<pass>`.
#cloud.auth:

# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ${ES_HOST}

  # Protocol - either `http` (default) or `https`.
  #protocol: "https"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: ${ES_USERNAME}
  password: ${ES_PASSWORD}

  # Enable to allow sending output to older ES versions
  allow_older_versions: true

# ================================= Processors =================================
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_cluster_id: ~

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
logging.level: debug

# Enable debug output for selected components. To enable all selectors use ["*"]
# Other available selectors are "beat", "publisher", "service"
# Multiple selectors can be chained.
#logging.selectors: ["publisher"]

# Send all logging output to stderr. The default is false.
#logging.to_stderr: false
