# A simple example of ClusterConfig object:
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name:
  region: eu-west-1
  version: "1.23"
  tags:
    division: engineering
    org: security
    team: contextual-security
    project: eks-simple-cluster # change this to reflect your project

vpc:
  # Don't change vpc settings
  id: "vpc-6cb55a15" # (optional, must match VPC ID used for each subnet below)
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    public:
      eu-west-1a:
        id: "subnet-d4cf96b2"

      eu-west-1b:
        id: "subnet-b50028fd"

      eu-west-1c:
        id: "subnet-7a841e20"

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
