name: Publish Cloudbeat

on:
  push:
    branches:
      - main

env:
  CLOUDBEAT_REGISTRY: ${{ secrets.AWS_ECR_ID_DEVELOP }}.dkr.ecr.${{ secrets.AWS_ECR_REGION_DEVELOP }}.amazonaws.com
  AWS_ECR_KEY: ${{ secrets.AWS_ECR_KEY_DEVELOP }}
  AWS_ECR_SECRET: ${{ secrets.AWS_ECR_SECRET_DEVELOP }}
  AWS_ECR_REGION: ${{ secrets.AWS_ECR_REGION_DEVELOP }}

jobs:
  publish_image_cloudbeat:
    name: Push Cloudbeat Docker image to ECR
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CLOUDBEAT_REGISTRY }}
          username: ${{ secrets.AWS_ECR_KEY_DEVELOP }}
          password: ${{ secrets.AWS_ECR_SECRET_DEVELOP }}

      - name: Fetch Go version from .go-version
        run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build Cloudbeat
        run: |
            GOOS=linux go build -v && docker build -t cloudbeat .

      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ env.AWS_ECR_KEY }}
          secret-access-key: ${{ env.AWS_ECR_SECRET }}
          region: ${{ env.AWS_ECR_REGION }}
          local-image: cloudbeat:latest
          image: cloudbeat:${{ github.sha }}, cloudbeat:csp-latest
