name: Sync Cloudbeat Versions on release
# Makes sure all cloudbeat versions are updated with release branches
on:
  # push:
  #   branches:
  #     # matches branches pushed by elasticmachine, e.g. "update-version-next-8.15.3"
  #     - 'update-version-next-*'
  workflow_dispatch: {}

jobs:
  synchronize-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the branch
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.CLOUDSEC_MACHINE_TOKEN }}
      - name: Synchronize versions using a script
        env:
          GH_TOKEN: ${{ secrets.CLOUDSEC_MACHINE_TOKEN }}
        run: |
          ./scripts/sync_internal_cloudbeat_version.sh
