name: Test Policies

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-rego-policies:
    name: Test Rego Policies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: OPA format
        uses: docker://openpolicyagent/opa:0.45.0
        with:
          args: "fmt ./bundle --fail=true --diff"

      - name: OPA format list failed files
        uses: docker://openpolicyagent/opa
        if: always()
        with:
          args: "fmt ./bundle --list"

      - name: OPA build
        uses: docker://openpolicyagent/opa
        with:
          args: "build -b ./bundle -e ./bundle/compliance"

      - name: OPA test
        uses: docker://openpolicyagent/opa
        with:
          args: "test -b ./bundle -v"

      - name: OPA check -strict
        uses: docker://openpolicyagent/opa
        with:
          args: "check --strict --bundle ./bundle"

  update-rules-status:
    name: Update rules status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Update rules status
        run: poetry run python ./dev/update_rule_status.py

      - name: Fail Rules.md is not updated - to fix run our pre-commit hooks
        run: git diff --exit-code

  update-rule-metadata:
    name: Update rules metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Update rule metadata
        run: poetry run python ./dev/generate_rule_metadata.py

      - name: Rule metadata mismatch - to fix run our pre-commit hooks
        run: git diff --exit-code