name: pytest integration tests

on:
  push:
    branches:
      - "ci-actions-testing-V2"
  # pull_request_target:
  #   branches:
  #     - main
  #   types: [assigned, opened, synchronize, reopened]

env:
  K8S_MANIFEST_DIR: deploy/k8s
  GO_VERSION: 1.17.2

jobs:
  pytest-integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ (github.event.pull_request_target || github.event.pull_request).head.repo.full_name }}
          ref: ${{ (github.event.pull_request_target || github.event.pull_request).head.sha }}
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: deploy/k8s/kind/kind-config.yaml
          cluster_name: kind-mono 

      - name: Docker build Cloudbeat
        run: |
          GOOS=linux go build -v && docker build -t cloudbeat . && kind load docker-image cloudbeat:latest --name kind-mono
      
      - name: Docker build tests-container
        run: |
          cd tests; docker build -t cloudbeat-test:0.0.6 . && kind load docker-image cloudbeat-test:0.0.6 --name kind-mono
      
      - uses: azure/setup-helm@v1
        id: install
      
      - name: Deploy tests Helm chart
        run: |
          helm upgrade --wait --install --values tests/deploy/k8s-cloudbeat-tests/k8s-values.yaml --namespace kube-system --kube-context kind-kind-mono cloudbeat-tests  tests/deploy/k8s-cloudbeat-tests/ 

      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 100s

      - name: run tests
        run: |
          helm test cloudbeat-tests --namespace kube-system --kube-context kind-kind-mono --logs